function Hd = ellip_band_filter
%ELLIP_BAND_FILTER 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
% Generated on: 03-Aug-2023 13:45:37

% Elliptic Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 226.2443;  % Sampling Frequency

N      = 20;   % Order
Fpass1 = 0.8;  % First Passband Frequency
Fpass2 = 2;    % Second Passband Frequency
Apass  = 20;    % Passband Ripple (dB)
Astop  = 80;   % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.bandpass('N,Fp1,Fp2,Ast1,Ap,Ast2', N, Fpass1, Fpass2, ...
                      Astop, Apass, Astop, Fs);
Hd = design(h, 'ellip');

% [EOF]
